#!/bin/bash

# Try to determine where is this script located.
MY_HOME="$( command -v -- "$0" 2>/dev/null )"
[ -z "$MY_HOME" ] && MY_HOME="$( command -v -- "${BASH_SOURCE[0]}" 2>/dev/null )"
MY_HOME="$( dirname -- "$MY_HOME" )"
MY_HOME="$( cd "$MY_HOME" && echo "$PWD" )"

exec env \
    PYTHONPATH="$PYTHONPATH:$MY_HOME" \
    python -m zebra.my_owm "$@"
